const langs = {
  EN: {
    menu: "Menu",
    service: "Service",
    reviews: "Feedback",
    about: "About",
    photos: "Photos",
    instructions: "Instructions",
    price: "Price",
    add: "Add",
    subtotal: "Subtotal",
    vieworder: "View Order",
    close: "Close",
    yourorder: "Your Order",
    placeorder: "Place Order",
    writeareview: "Write a Review",
    addreview: "Add review",
    ourmenus: "Our Menus",
    bookatable: "Book a Table",
    needwaiter: "Call Waiter",
    needinvoice: "Request Bill",
    needvalet: "Valet",
    updateitem: "Update Item",
    login: "Login",
    loginwithyourphonenumber: "Log in with your phone number",
    phone: "Phone",
    password: "Password",
    signin: "Sign In",
    forgetpassword: "Forget Password",
    notamemberyet: "Not a member yet",
    signupnow: "Sign Up Now",
    register: "Register",
    createnewaccount: "Create new account",
    firstname: "First Name",
    lastname: "Last Name",
    fullname: "Full Name",
    phoneoremail: "Phone or Email",
    email: "Email",
    confirmpassword: "Confirm Password",
    signup: "Sign Up",
    alreadyamember: "Already a Member",
    signinnow: "Sign In Now",
    requestcode: "Request Code",
    noworriesmsg: "No worries, we've got your back! Submit your email",
    validation: "Validation",
    code: "Code",
    submitcode: "Submit Code",
    validationmsg:
      "We've texted you a code to your email. Oncce you receive the code, enter it below to",
    resetyourpassword: "Reset your password",
    validateyouraccount: "validate your account",
    includeditems: " Included Items",
    selection: "Selection",
    additem: "Add Item",
    deliveryaddress: "Delivery Address",
    label: "Label",
    street: "Street",
    city: "City",
    state: "State",
    near: "Near",
    zipcode: "Zip, Postal Code",
    apartment: "Apartment",
    floor: "Floor",
    remark: "Remark",
    erroroccured: "Error Occured",
    errorconnection: "Error Connection",
    addresssavingfailed: "Address Saving Failed",
    pleasefillrequired: "Please fill all required inputs",
    registrationfailed: "Registration Failed",
    logindone: "Login Done Successfully",
    loginsuccess: "Login Success",
    invalidcredentials: "Invalid Credentials",
    loginfailed: "Login Failed",
    invalidemail: "Invalid Email",
    requestcodefailed: "Request Code Failed",
    invalidcode: "Invalid Code",
    submitcodefailed: "Submit Code Failed",
    resetpasswordfailed: "Reset Password Failed",
    pleaseconfirmyourpassword: "Please Confirm Your Password",
    registrationdone: "Registration Done Successfully",
    registrationsuccess: "Registration Success",
    phonealreadyexist: "Phone Already Exist",
    emailalreadyexist: "Email Already Exist",
    reviewsaved: "Review Saved Successfully",
    reviewsuccess: "Review Success",
    reviewfailed: "Review Failed",
    waiterwillbewithyou:
      "Thank you for your request. Someone will be with you shortly!",
    invoicewillbewithyou: "Sure! Someone will get it for you shortly",
    valetwillbewithyou: "Taking care of it, We thank you for your visit!",
    requestsuccess: "Request Success",
    requestfailed: "Request Failed",
    reservationsuccess: "Reservation Success",
    reservationfaailed: "Reservation Failed",
    reservationdone: "Reservation Done Successfully",
    youhavetologinbefore: "You have to login before saving your order",
    thankyouforyourorder:
      "Thank you for your order! We will let you know as soon as it is accepted and processed.",
    ordernotsaved: "Order not saved",
    logoutmsg: "Would you like to Logout",
    reviewprofile: "Review Profile",
    infooptional: "These info are optional",
    submitreview: "Submit Review",
    minimumorder: "Minimum Order",
    deliverylater: "Deliver Later",
    pickup: "Pick Up",
    submitreservation: "Submit Reservation",
    dateshouldbegreater: "Reservation date should be greater than current date",
    minimumcharge: "Minimum Charge",
    dateshouldbeless:
      "Not allowed to  add reservation for date greater than 4 month from today!",
    dateandtime: "Date & Time",
    notes: "Notes",
    guests: "Guests",
    cashondelivery: "Cash on Delivery",
    creditcard: "Credit Card",
    submit: "Submit",
    yourcomments: "Your Comments",
    appreciatecomment: "We appreciate your comments",
    rateyourexperience: "Rate your experience",
    calories: "Calories",
    loyalty: "Loyalty",
    rewards: "Rewards",
  },
  FR: {
    menu: "Menu",
    service: "Service",
    reviews: "Commentaires",
    about: "À propos",
    photos: "Photos",
    instructions: "Instructions",
    price: "Prix",
    add: "ajouter",
    subtotal: "Total",
    vieworder: "Voir l'ordre",
    close: "Fermer",
    yourorder: "Votre commande",
    placeorder: "Passer la commande",
    writeareview: "Écrire une critique",
    addreview: "Ajouter un commentaire",
    ourmenus: "Nos menus",
    bookatable: "Réserver une table",
    needwaiter: "Besoin d'un serveur",
    needinvoice: "Demande de facture",
    needvalet: "Appeler le service de voiturier",
    updateitem: "Mettre à jour le produit",
    login: "S'identifier",
    loginwithyourphonenumber: "Connectez-vous avec votre numéro de téléphone",
    phone: "Téléphone",
    password: "Mot de passe",
    signin: "Se connecter",
    forgetpassword: "Mot de passe oublié",
    notamemberyet: "Pas encore membre",
    signupnow: "S'inscrire maintenant",
    register: "S'inscrire",
    createnewaccount: "Créer un nouveau compte",
    firstname: "Prénom",
    lastname: "Nom de famille",
    fullname: "Nom et prénom",
    phoneoremail: "Téléphone ou email",
    email: "Email",
    confirmpassword: "Confirmez le mot de passe",
    signup: "S'inscrire",
    alreadyamember: "Déjà membre",
    signinnow: "Connectez vous maintenant",
    requestcode: "Code requis",
    noworriesmsg:
      "Pas de soucis, nous sommes là pour vous! Soumettez votre email",
    validation: "Validation",
    code: "Code",
    submitcode: "Soumettre le code",
    validationmsg:
      "Nous vous avons envoyé un code par e-mail. Une fois que vous recevez le code, entrez-le ci-dessous pour",
    resetyourpassword: "réinitialisez votre mot de passe",
    validateyouraccount: "valider votre compte",
    includeditems: "Produit inclus",
    selection: "Sélection",
    additem: "ajouter un produit",
    deliveryaddress: "Adresse de livraison",
    label: "Étiquette",
    street: "rue",
    city: "Ville",
    state: "Etat",
    near: "Près",
    zipcode: "Code postal",
    apartment: "Appartement",
    floor: "Etage",
    remark: "Remarque",
    erroroccured: "Erreur est survenue",
    errorconnection: "Erreur de connexion",
    addresssavingfailed: "Échec de l'enregistrement d'adresse",
    pleasefillrequired: "Veuillez remplir toutes les entrées requises",
    registrationfailed: "Échec de l'enregistrement",
    logindone: "Connexion terminée avec succès",
    loginsuccess: "Connexion réussie",
    invalidcredentials: "Les informations d'identification invalides",
    loginfailed: "Échec de la connexion",
    invalidemail: "Email invalide",
    requestcodefailed: "Le code de demande a échoué",
    invalidcode: "Code invalide",
    submitcodefailed: "Échec de la soumission du code",
    resetpasswordfailed: "Échec de la réinitialisation du mot de passe",
    pleaseconfirmyourpassword: "Veuillez confirmer votre mot de passe",
    registrationdone: "Inscription réussie",
    registrationsuccess: "Inscription réussie",
    phonealreadyexist: "Le téléphone existe déjà",
    emailalreadyexist: "L'e-mail existe déjà",
    reviewsaved: "Avis enregistré avec succès",
    reviewsuccess: "Évaluation du succès",
    reviewfailed: "La révision a échoué",
    waiterwillbewithyou:
      "Merci pour votre requête. Quelqu'un sera avec vous sous peu!",
    invoicewillbewithyou: "Sûr! Quelqu'un le récupérera sous peu",
    valetwillbewithyou:
      "En prenant soin de lui, nous vous remercions de votre visite!",
    requestsuccess: "Demande de succès",
    requestfailed: "Demande échoué",
    reservationsuccess: "Réservation réussie",
    reservationfaailed: "La réservation a échoué",
    reservationdone: "Réservation effectuée avec succès",
    youhavetologinbefore:
      "Vous devez vous connecter avant de sauvegarder votre commande",
    thankyouforyourorder:
      "Merci pour votre temps, votre commande est enregistrée",
    ordernotsaved: "Commande non enregistrée",
    logoutmsg: "Souhaitez-vous vous déconnecter",
    reviewprofile: "Profil de révision",
    infooptional: "Ces informations sont facultatives",
    submitreview: "Poster le commentaire",
    minimumorder: "Commande minimum",
    deliverylater: "Livraison plus tard",
    pickup: "Récupérer",
    submitreservation: "Soumettre la réservation",
    dateshouldbegreater:
      "La date de réservation doit être supérieure à la date actuelle",
    minimumcharge: "Charge minimale",
    dateshouldbeless:
      "Non autorisé à ajouter une réservation pour une date supérieure à 4 mois à partir d'aujourd'hui!",
    dateandtime: "Date et heure",
    notes: "Remarques",
    guests: "Invités",
    cashondelivery: "Paiement à la livraison",
    creditcard: "Carte de crédit",
    submit: "Soumettre",
    yourcomments: "Vos commentaires",
    appreciatecomment: "Nous apprécions vos commentaires",
    rateyourexperience: "Évaluez votre expérience",
    calories: "Calories",
    loyalty: "Fidélité",
    rewards: "Récompenses",
  },
  AR: {
    menu: "قائمة الطعام",
    service: "الخدمات",
    reviews: "المراجعات",
    about: "حول",
    photos: "الصور",
    instructions: "تعليمات",
    price: "السعر",
    add: "أضف",
    subtotal: "المجموع",
    vieworder: "مشاهدة الطلب",
    close: "أغلق",
    yourorder: "طلبك",
    placeorder: "ارسال الطلب",
    writeareview: "أكتب مراجعة",
    addreview: "إضافة مراجعة",
    ourmenus: "قوائمنا",
    bookatable: "احجز طاولة",
    needwaiter: "تحتاج النادل",
    needinvoice: "طلب الفاتورة",
    needvalet: "استدعاء خادم وقوف السيارات",
    updateitem: "تحديث المنتج",
    login: "تسجيل الدخول",
    loginwithyourphonenumber: "سجل الدخول برقم هاتفك",
    phone: "هاتف",
    password: "كلمه السر",
    signin: "تسجيل الدخول",
    forgetpassword: "نسيت كلمة المرور",
    notamemberyet: "لست عضوا حتى الآن",
    signupnow: "أفتح حساب الأن",
    register: "تسجيل",
    createnewaccount: "انشاء حساب جديد",
    firstname: "الاسم",
    lastname: "الكنية",
    fullname: "الاسم الكامل",
    phoneoremail: "الهاتف أو البريد الإلكتروني",
    email: "البريد الإلكتروني",
    confirmpassword: "تأكيد كلمة المرور",
    signup: "سجل",
    alreadyamember: "عضوا فعلا",
    signinnow: "قم بتسجيل دخولك الآن",
    requestcode: "اطلب الرمز",
    noworriesmsg: "لا تقلق ، نحن نساندك! أرسل بريدك الإلكتروني",
    validation: "التحقق من الصحة",
    code: "الرمز",
    submitcode: "إرسال الرمز",
    validationmsg:
      "لقد أرسلنا لك رمزًا نصيًا إلى بريدك الإلكتروني. بمجرد استلام الرمز ، أدخله أدناه إلى",
    resetyourpassword: "اعد ضبط كلمه السر",
    validateyouraccount: "التحقق من صحة حسابك",
    includeditems: "المنتجات المدرجة",
    selection: "اختيار",
    additem: "أضف منتج",
    deliveryaddress: "عنوان التسليم",
    label: "ملصق",
    street: "شارع",
    city: "مدينة",
    state: "حالة",
    near: "قريب",
    zipcode: "الرمز البريدي",
    apartment: "شقة",
    floor: "أرضية",
    remark: "ملاحظة",
    erroroccured: "حدث خطأ",
    errorconnection: "اتصال خطأ",
    addresssavingfailed: "فشل حفظ العنوان",
    pleasefillrequired: "يرجى ملء جميع المدخلات المطلوبة",
    registrationfailed: "فشل في التسجيل",
    logindone: "تم تسجيل الدخول بنجاح",
    loginsuccess: "النجاح في تسجيل الدخول",
    invalidcredentials: "بيانات الاعتماد غير صالحة",
    loginfailed: "فشل تسجيل الدخول",
    invalidemail: "بريد إلكتروني خاطئ",
    requestcodefailed: "طلب رمز فشل",
    invalidcode: "الرمز غير صحيح",
    submitcodefailed: "إرسال الرمز فشل",
    resetpasswordfailed: "فشل إعادة تعيين كلمة المرور",
    pleaseconfirmyourpassword: "يرجى تأكيد كلمة المرور الخاصة بكd",
    registrationdone: "تم التسجيل بنجاح",
    registrationsuccess: "نجاح التسجيل",
    phonealreadyexist: "الهاتف موجود بالفعل",
    emailalreadyexist: "البريد الالكتروني موجود مسبقا",
    reviewsaved: "تم حفظ المراجعة بنجاح",
    reviewsuccess: "مراجعة النجاح",
    reviewfailed: "فشلت المراجعة",
    waiterwillbewithyou: "شكرا لطلبك. شخص ما سيكون معك قريبا!",
    invoicewillbewithyou: "أكيد! شخص ما سيحصل عليه لك قريبا",
    valetwillbewithyou: "العناية بها نشكركم على زيارتكم!",
    requestsuccess: "طلب النجاح",
    requestfailed: "الطلب فشل",
    reservationsuccess: "نجاح الحجز",
    reservationfaailed: "فشل الحجز",
    reservationdone: "تم الحجز بنجاح",
    youhavetologinbefore: "يجب عليك تسجيل الدخول قبل حفظ طلبك",
    thankyouforyourorder: "شكرا لك على وقتك ، تم حفظ طلبك",
    ordernotsaved: "لم يتم حفظ الطلب",
    logoutmsg: "هل تريد تسجيل الخروج",
    reviewprofile: "مراجعة الملف الشخصي",
    infooptional: "هذه المعلومات اختيارية",
    submitreview: "إرسال المراجعة",
    minimumorder: "الحد الأدنى للطلب",
    deliverylater: "التسليم في وقت لاحق",
    pickup: "الاستلام",
    submitreservation: "إرسال الحجز",
    dateshouldbegreater: "يجب أن يكون تاريخ الحجز أكبر من التاريخ الحالي",
    minimumcharge: "الحد الأدنى للطلب",
    dateshouldbeless: "غير مسموح بإضافة حجز لتاريخ أكبر من 4 أشهر من اليوم!",
    dateandtime: "التاريخ والوقت",
    notes: "ملاحظات",
    guests: "ضيوف",
    cashondelivery: "نقدا عند الاستلام",
    creditcard: "بطاقة ائتمان",
    submit: "إرسال",
    yourcomments: "تعليقاتك",
    appreciatecomment: "نحن نقدر تعليقاتك",
    rateyourexperience: "قيم تجربتك",
    calories: "سعرات حراريه",
    loyalty: "وفاء",
    rewards: "المكافآت",
  },
};
